name: backup-daily

on:
  workflow_dispatch:
  schedule:
    - cron: 0 6 * * *

jobs:
  s3-backup-daily:
    uses: narrative-io/common-github/.github/workflows/backup.yml@c8c12dcd280c68e5e406545d12153195ce8e0f03
    secrets: inherit
