name: backup-daily

on:
  workflow_dispatch:
  schedule:
    - cron: 0 6 * * *

jobs:
  s3-backup-daily:
    uses: narrative-io/common-github/.github/workflows/backup.yml@1db734d3deea22b1226107c87291b0e2e4a9f785
    secrets: inherit
